export const dwarf = new Map([
  [
    1,
    {
      level: 1,
      attack: 'd3',
      critDie: '1d10',
      critTable: 'III',
      actionDice: '1d20',
      ref: 1,
      fort: 1,
      will: 1,
    },
  ],
  [
    2,
    {
      level: 2,
      attack: 'd4',
      critDie: '1d12',
      critTable: 'III',
      actionDice: '1d20',
      ref: 1,
      fort: 1,
      will: 1,
    },
  ],
  [
    3,
    {
      level: 3,
      attack: 'd5',
      critDie: '1d14',
      critTable: 'III',
      actionDice: '1d20',
      ref: 1,
      fort: 2,
      will: 1,
    },
  ],
  [
    4,
    {
      level: 4,
      attack: 'd6',
      critDie: '1d16',
      critTable: 'IV',
      actionDice: '1d20',
      ref: 2,
      fort: 2,
      will: 2,
    },
  ],
  [
    5,
    {
      level: 5,
      attack: 'd7',
      critDie: '1d20',
      critTable: 'IV',
      actionDice: '1d20+1d14',
      ref: 2,
      fort: 3,
      will: 2,
    },
  ],
  [
    6,
    {
      level: 6,
      attack: 'd8',
      critDie: '1d24',
      critTable: 'V',
      actionDice: '1d20+1d16',
      ref: 2,
      fort: 4,
      will: 2,
    },
  ],
  [
    7,
    {
      level: 7,
      attack: 'd10+1',
      critDie: '1d30',
      critTable: 'V',
      actionDice: '1d20+1d20',
      ref: 3,
      fort: 4,
      will: 3,
    },
  ],
  [
    8,
    {
      level: 8,
      attack: 'd10+2',
      critDie: '1d30',
      critTable: 'V',
      actionDice: '1d20+1d20',
      ref: 3,
      fort: 5,
      will: 3,
    },
  ],
  [
    9,
    {
      level: 9,
      attack: 'd10+3',
      critDie: '2d20',
      critTable: 'V',
      actionDice: '1d20+1d20',
      ref: 3,
      fort: 5,
      will: 3,
    },
  ],
  [
    10,
    {
      level: 10,
      attack: 'd10+4',
      critDie: '2d20',
      critTable: 'V',
      actionDice: '1d20+1d20+1d14',
      ref: 4,
      fort: 6,
      will: 4,
    },
  ],
]);
