export const halfling = new Map([
  [
    1,
    {
      level: 1,
      attack: 1,
      critDie: '1d8',
      critTable: 'III',
      actionDie: '1d20',
      ref: 1,
      fort: 1,
      will: 1,
      sneakAndHide: 3,
    },
  ],
  [
    2,
    {
      level: 2,
      attack: 2,
      critDie: '1d8',
      critTable: 'III',
      actionDie: '1d20',
      ref: 1,
      fort: 1,
      will: 1,
      sneakAndHide: 5,
    },
  ],
  [
    3,
    {
      level: 3,
      attack: 2,
      critDie: '1d10',
      critTable: 'III',
      actionDie: '1d20',
      ref: 2,
      fort: 1,
      will: 2,
      sneakAndHide: 7,
    },
  ],
  [
    4,
    {
      level: 4,
      attack: 3,
      critDie: '1d10',
      critTable: 'III',
      actionDie: '1d20',
      ref: 2,
      fort: 2,
      will: 2,
      sneakAndHide: 8,
    },
  ],
  [
    5,
    {
      level: 5,
      attack: 4,
      critDie: '1d12',
      critTable: 'III',
      actionDie: '1d20',
      ref: 3,
      fort: 2,
      will: 3,
      sneakAndHide: 9,
    },
  ],
  [
    6,
    {
      level: 6,
      attack: 5,
      critDie: '1d12',
      critTable: 'III',
      actionDie: '1d20+1d14',
      ref: 4,
      fort: 2,
      will: 4,
      sneakAndHide: 11,
    },
  ],
  [
    7,
    {
      level: 7,
      attack: 5,
      critDie: '1d14',
      critTable: 'III',
      actionDie: '1d20+1d16',
      ref: 4,
      fort: 3,
      will: 4,
      sneakAndHide: 12,
    },
  ],
  [
    8,
    {
      level: 8,
      attack: 6,
      critDie: '1d14',
      critTable: 'III',
      actionDie: '1d20+1d20',
      ref: 5,
      fort: 3,
      will: 5,
      sneakAndHide: 13,
    },
  ],
  [
    9,
    {
      level: 9,
      attack: 7,
      critDie: '1d16',
      critTable: 'III',
      actionDie: '1d20+1d20',
      ref: 5,
      fort: 3,
      will: 5,
      sneakAndHide: 14,
    },
  ],
  [
    10,
    {
      level: 10,
      attack: 8,
      critDie: '1d16',
      critTable: 'III',
      actionDie: '1d20+1d20',
      ref: 6,
      fort: 4,
      will: 6,
      sneakAndHide: 15,
    },
  ],
]);
