export const thief = new Map([
  [
    1,
    {
      level: 1,
      attack: 0,
      critDie: '1d10',
      critTable: 'II',
      actionDice: '1d20',
      luckDie: 'd3',
      ref: 1,
      fort: 1,
      will: 0,
    },
  ],
  [
    2,
    {
      level: 2,
      attack: 1,
      critDie: '1d12',
      critTable: 'II',
      actionDice: '1d20',
      luckDie: 'd4',
      ref: 1,
      fort: 1,
      will: 0,
    },
  ],
  [
    3,
    {
      level: 3,
      attack: 2,
      critDie: '1d14',
      critTable: 'II',
      actionDice: '1d20',
      luckDie: 'd5',
      ref: 2,
      fort: 1,
      will: 1,
    },
  ],
  [
    4,
    {
      level: 4,
      attack: 2,
      critDie: '1d16',
      critTable: 'II',
      actionDice: '1d20',
      luckDie: 'd6',
      ref: 2,
      fort: 2,
      will: 1,
    },
  ],
  [
    5,
    {
      level: 5,
      attack: 3,
      critDie: '1d20',
      critTable: 'II',
      actionDice: '1d20',
      luckDie: 'd7',
      ref: 3,
      fort: 2,
      will: 1,
    },
  ],
  [
    6,
    {
      level: 6,
      attack: 4,
      critDie: '1d24',
      critTable: 'II',
      actionDice: '1d20+1d14',
      luckDie: 'd8',
      ref: 4,
      fort: 2,
      will: 2,
    },
  ],
  [
    7,
    {
      level: 7,
      attack: 5,
      critDie: '1d30',
      critTable: 'II',
      actionDice: '1d20+1d16',
      luckDie: 'd10',
      ref: 4,
      fort: 3,
      will: 2,
    },
  ],
  [
    8,
    {
      level: 8,
      attack: 5,
      critDie: '1d30+2',
      critTable: 'II',
      actionDice: '1d20+1d20',
      luckDie: 'd12',
      ref: 5,
      fort: 3,
      will: 2,
    },
  ],
  [
    9,
    {
      level: 9,
      attack: 6,
      critDie: '1d30+4',
      critTable: 'II',
      actionDice: '1d20+1d20',
      luckDie: 'd14',
      ref: 5,
      fort: 3,
      will: 3,
    },
  ],
  [
    10,
    {
      level: 10,
      attack: 7,
      critDie: '1d30+6',
      critTable: 'II',
      actionDice: '1d20+1d20',
      luckDie: 'd16',
      ref: 5,
      fort: 4,
      will: 3,
    },
  ],
]);
