export const wizard = new Map([
  [
    1,
    {
      level: 1,
      attack: 0,
      critDie: '1d6',
      critTable: 'I',
      actionDice: '1d20',
      knownSpells: 4,
      maxSpellLevel: 1,
      ref: 1,
      fort: 0,
      will: 1,
    },
  ],
  [
    2,
    {
      level: 2,
      attack: 1,
      critDie: '1d6',
      critTable: 'I',
      actionDice: '1d20',
      knownSpells: 5,
      maxSpellLevel: 1,
      ref: 1,
      fort: 0,
      will: 1,
    },
  ],
  [
    3,
    {
      level: 3,
      attack: 1,
      critDie: '1d8',
      critTable: 'I',
      actionDice: '1d20',
      knownSpells: 6,
      maxSpellLevel: 2,
      ref: 1,
      fort: 1,
      will: 2,
    },
  ],
  [
    4,
    {
      level: 4,
      attack: 1,
      critDie: '1d8',
      critTable: 'I',
      actionDice: '1d20',
      knownSpells: 7,
      maxSpellLevel: 2,
      ref: 2,
      fort: 1,
      will: 2,
    },
  ],
  [
    5,
    {
      level: 5,
      attack: 2,
      critDie: '1d10',
      critTable: 'I',
      actionDice: '1d20+1d14',
      knownSpells: 8,
      maxSpellLevel: 3,
      ref: 2,
      fort: 1,
      will: 3,
    },
  ],
  [
    6,
    {
      level: 6,
      attack: 2,
      critDie: '1d10',
      critTable: 'I',
      actionDice: '1d20+1d16',
      knownSpells: 9,
      maxSpellLevel: 3,
      ref: 2,
      fort: 2,
      will: 4,
    },
  ],
  [
    7,
    {
      level: 7,
      attack: 3,
      critDie: '1d12',
      critTable: 'I',
      actionDice: '1d20+1d20',
      knownSpells: 10,
      maxSpellLevel: 4,
      ref: 3,
      fort: 2,
      will: 4,
    },
  ],
  [
    8,
    {
      level: 8,
      attack: 3,
      critDie: '1d12',
      critTable: 'I',
      actionDice: '1d20+1d20',
      knownSpells: 12,
      maxSpellLevel: 4,
      ref: 3,
      fort: 2,
      will: 5,
    },
  ],
  [
    9,
    {
      level: 9,
      attack: 4,
      critDie: '1d14',
      critTable: 'I',
      actionDice: '1d20+1d20',
      knownSpells: 14,
      maxSpellLevel: 5,
      ref: 4,
      fort: 3,
      will: 5,
    },
  ],
  [
    10,
    {
      level: 10,
      attack: 4,
      critDie: '1d14',
      critTable: 'I',
      actionDice: '1d20+1d20+1d14',
      knownSpells: 16,
      maxSpellLevel: 5,
      ref: 4,
      fort: 3,
      will: 6,
    },
  ],
]);
